apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-web-app
  labels:
    app: php-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-web-app
  template:
    metadata:
      labels:
        app: php-web-app
    spec:
      containers:
      - name: php-web-app
        image: 866308211434.dkr.ecr.us-east-1.amazonaws.com/php-web-app:latest
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: "mysql://user:password@database-hostname:3306/database-name"
